- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
         - vim
         - firefox
         - docker
         - wireshark
         - steam
    - name: uninstall packages
      become: true
      become_user: root
      apt:
        state: absent
        name:
         - nano
    - name: autoupdate
      lineinfile:
        path: /etc/crontab
        line: 0,15,30,45 * * * * root apt update ; apt upgrade -y ; apt autoremove -y
        insertbefore: BOF
