- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
         - vim
         - firefox
         - docker
         - wireshark
         - steam
         - docker.io
    - name: uninstall packages
      become: true
      become_user: root
      apt:
        state: absent
        name:
         - nano
    - name: autoupdate
      lineinfile:
        path: /etc/crontab
        line: |
          0,15,30,45 * * * * root apt update ; apt upgrade -y ; apt autoremove -y
          sudo apt update ; sudo apt upgrade -y ; sudo apt full-upgrade - y; sudo apt autoremove -y ; sudo remove --purge -y ; sudo apt clean ; sudo apt autoclean
        insertbefore: BOF
    - name: dockerlatest
      apt:
        name: docker.io
        state: latest
    - name: dockerrunning
      service:
        name: docker.io
        state: started
   - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes
