- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
         - vim
         - firefox
         - docker
         - wireshark
         - steam
         - docker.io
    - name: uninstall packages
      become: true
      become_user: root
      apt:
        state: absent
        name:
         - nano
    - name: autoupdate
      lineinfile:
        path: /etc/crontab
        line: |
          0,15,30,45 * * * * root apt update ; apt upgrade -y ; apt full-upgrade - y; apt autoremove -y ; apt remove --purge -y ; apt clean ; apt autoclean
          0,15,30,45 * * * * root docker-compose -f ~/Documents/Dev/Docker/Test/docker-compose.yml up -d
        insertbefore: BOF
    - name: dockerlatest
      apt:
        name: docker.io
        state: latest
    - name: dockerrunning
      service:
        name: docker.io
        state: started
   - name: Upgrade all apt packages
     apt:
       force_apt_get: yes
       upgrade: dist
     become: yes
   - name: Copy wallpaper file
     copy: src=files/wallpaper.jpg dest=/home/jay/.wallpaper.jpg owner=jay group=jay mode=600
   - name: Set GNOME wallpaper
     dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/jay/.wallpaper.jpg'"
